(() => {
  'use strict';
  const C=StockFlowCore,F=StockFlowAPI,app=document.querySelector('#app'),modal=document.querySelector('#modal');
  const S={store:null,db:C.blank(),view:'dashboard',cart:[],search:'',category:'All categories',historySearch:'',historyDate:'',historyStatus:'all',customer:'',customerPhone:'+62',payment:'Cash',note:'',busy:false,ready:false,syncError:'',lastSync:null};
  const icons={box:'<path d="m4 7 8-4 8 4v10l-8 4-8-4zM4 7l8 4 8-4M12 11v10M8 5l8 4"/>',dashboard:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',sale:'<path d="M3 3h2l3 13h10l3-9H6M10 21h.01M18 21h.01"/>',history:'<path d="M3 11a9 9 0 1 1 2 7M3 4v7h7M12 7v5l3 2"/>',settings:'<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="9" cy="18" r="2"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',plus:'<path d="M12 5v14M5 12h14"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',logout:'<path d="M9 4H4v16h5m5-12 4 4-4 4M8 12h13"/>',check:'<path d="m5 12 4 4L19 6"/>',refresh:'<path d="M20 8a8 8 0 0 0-14-3L3 8m0-5v5h5m-4 8a8 8 0 0 0 14 3l3-3m0 5v-5h-5"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',alert:'<path d="m12 3 10 18H2zM12 9v5m0 3h.01"/>',receipt:'<path d="M5 3h14v18l-3-2-4 2-4-2-3 2zM8 7h8M8 11h8M8 15h4"/>',phone:'<path d="M6.6 2.8 9 7.2 6.8 9c1.3 2.7 3.5 4.9 6.2 6.2l1.8-2.2 4.4 2.4-.7 3.2c-.2.9-1 1.5-2 1.4C9.6 19.2 4.8 14.4 4 7.5c-.1-1 .5-1.8 1.4-2z"/>',qr:'<path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM15 14h2v2h-2zM18 14h2v5h-2zM14 18h3v2h-3z"/>',user:'<circle cx="12" cy="8" r="3"/><path d="M5 21c.8-4 3.1-6 7-6s6.2 2 7 6"/>'};
  const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.box}</svg>`;
  const esc=x=>String(x??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
  const money=n=>'Rp '+Number(n||0).toLocaleString('id-ID');
  const IDR_PER_MYR=4333.17;
  const myr=n=>'MYR '+(Number(n||0)/IDR_PER_MYR).toFixed(2);
  const dualMoney=n=>`<span class="dual-money"><span>${money(n)}</span><small>${myr(n)}</small></span>`;
  const rm=n=>n==null?'Not supplied':'MYR '+Number(n).toFixed(2);
  const canonicalName=n=>n==='Imposter Bracelet'?'Beaded Bracelet 5':n;
  const when=t=>new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Jakarta',dateStyle:'medium',timeStyle:'short'}).format(new Date(t));
  const id=()=>crypto.randomUUID();
  const products=()=>Object.values(S.db.products).filter(p=>p.active).map(p=>p.name==='Imposter Bracelet'?{...p,name:'Beaded Bracelet 5'}:p).sort((a,b)=>a.sku.localeCompare(b.sku));
  const sales=()=>Object.values(S.db.sales).sort((a,b)=>b.at-a.at);
  const image=p=>p.image&&/^assets\/product-\d{2}\.jpg$/.test(p.image)?`<img src="${esc(p.image)}" alt="${esc(canonicalName(p.name))}" loading="lazy">`:`<span class="product-placeholder">${icon('box')}</span>`;
  function toast(msg,error=false){const el=document.querySelector('#toast');el.textContent=msg;el.className=error?'error':'';el.hidden=false;if(error&&modal.open){let alert=modal.querySelector('.modal-error');if(!alert){alert=document.createElement('p');alert.className='form-error modal-error';alert.setAttribute('role','alert');modal.append(alert);}alert.textContent=msg;}clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,error?10000:5000);}
  function pendingKey(){return 'stockflow_pending_'+S.store.actor().uid;}
  function pending(){try{return JSON.parse(sessionStorage.getItem(pendingKey())||'null');}catch{return null;}}
  function normalizePhone(value){let d=String(value||'').replace(/\D/g,'');if(!d)return '';if(d.startsWith('0'))d='62'+d.slice(1);else if(d.startsWith('8'))d='62'+d;return d;}
  function paymentQr(compact=false){return `<div class="payment-qr-card ${compact?'compact':''}"><button type="button" data-action="qr" aria-label="Open payment QR"><img src="assets/duitnow-qr.png" alt="DuitNow Malaysia National QR"></button><div><strong>Scan to pay</strong><small>DuitNow · Malaysia National QR</small>${compact?'':'<span>Tap the QR to enlarge</span>'}</div></div>`;}
  function invoiceText(s){const lines=[`*StockFlow E-Invoice*`,`StockFlow by Muhammad Irfan`,`Invoice #${s.id.slice(-8).toUpperCase()}`,`${when(s.at)} WIB`,`Customer: ${s.customer||'Walk-in customer'}`,'',...s.items.map(i=>`${i.quantity}× ${canonicalName(i.name)} — ${money(i.lineTotal)} (${myr(i.lineTotal)})`),'',`*Total: ${money(s.total)} (${myr(s.total)})*`,`Payment: ${s.payment}`];if(s.note)lines.push(`Note: ${s.note}`);if(s.payment==='QR / bank transfer')lines.push('Payment QR: available at the StockFlow counter.');lines.push('','Thank you for your purchase ✨');return lines.join('\n');}
  function sendWhatsApp(saleId){const s=S.db.sales[saleId],phone=normalizePhone(s.customerPhone);if(!phone||phone==='62'){toast('Add the customer WhatsApp number before sending the invoice.',true);return;}window.open(`https://wa.me/${phone}?text=${encodeURIComponent(invoiceText(s))}`,'_blank','noopener,noreferrer');}
  function showWelcome(){app.innerHTML=`<main class="welcome-screen"><div class="splash-glow splash-glow-a"></div><div class="splash-glow splash-glow-b"></div><div class="welcome-brand">${icon('box')}<span>StockFlow<span class="brand-dot">.</span></span><small>by Muhammad Irfan</small></div><div class="splash-stage" aria-hidden="true"><div class="splash-orbit orbit-one"></div><div class="splash-orbit orbit-two"></div><div class="splash-core">${icon('box')}<span class="splash-pulse"></span></div><span class="splash-dot dot-a"></span><span class="splash-dot dot-b"></span><span class="splash-dot dot-c"></span></div><div class="welcome-copy"><span>STOCKFLOW</span><h1>Business in motion.</h1><p>Connecting to your shared sales and inventory workspace…</p><div class="splash-progress"><i></i></div></div><div class="splash-foot">SALES · INVENTORY · E-INVOICE</div></main>`;}
  function openDialog(html){modal.innerHTML=`<button class="icon-button modal-close" data-action="close" aria-label="Close dialog">${icon('close')}</button>${html}`;modal.showModal();}
  function closeDialog(){if(!S.busy)modal.close();}
  function setBusy(value){S.busy=value;document.querySelectorAll('button,input,select,textarea').forEach(el=>{if(value){el.dataset.wasDisabled=el.disabled?'1':'0';el.disabled=true;}else{el.disabled=el.dataset.wasDisabled==='1';delete el.dataset.wasDisabled;}});}
  function headerStatus(){const el=document.querySelector('#sync-status');if(el)el.innerHTML=`<span class="status-dot ${S.syncError?'bad':''}"></span>${S.syncError?'Firebase connection needs attention':S.lastSync?'Connected to Firebase':'Connecting…'}`;const warning=document.querySelector('#sync-warning');if(warning){warning.hidden=!S.syncError;warning.innerHTML=S.syncError?`${esc(S.syncError)} <button class="text-button" data-action="refresh">Try again</button>`:'';}}
  function shell(){
    const nav=[['dashboard','dashboard','Overview'],['sale','sale','New sale'],['inventory','box','Inventory'],['history','history','Sales history'],['settings','settings','Setup']];
    app.innerHTML=`<div class="shell"><aside class="sidebar"><a class="brand" href="#" data-view="dashboard">${icon('box')}<span>StockFlow<span class="brand-dot">.</span></span></a><div class="brand-by">by Muhammad Irfan</div><div class="workspace-label">SHARED WORKSPACE</div><div class="workspace-name"><span class="workspace-avatar">S</span><div><strong>SUCCESS26</strong><small>Firebase RTDB · shared live data</small></div></div><nav aria-label="Main navigation">${nav.map(([view,i,label])=>`<button data-view="${view}" class="nav-item ${S.view===view?'active':''}" ${S.view===view?'aria-current="page"':''}>${icon(i)}${label}${view==='sale'?'<span class="nav-plus">+</span>':''}</button>`).join('')}</nav><div class="sidebar-note"><span class="eyebrow">KEEP IT FLOWING</span><p>Every item accounted for.<br>Every sale in one place.</p><div class="mini-boxes">${icon('box')}${icon('box')}${icon('box')}</div></div><div class="user-card"><span class="avatar">S</span><div><strong>Shared workspace</strong><small>No cashier login required</small></div></div></aside><div class="main-column"><header class="topbar"><div class="breadcrumb">StockFlow <span>/</span> <strong>${nav.find(n=>n[0]===S.view)?.[2]}</strong></div><span id="sync-status" class="sync-status"></span><button class="icon-button" data-action="refresh" aria-label="Refresh data">${icon('refresh')}</button></header><div id="sync-warning" class="sync-warning" role="alert" hidden></div><div id="pending-banner"></div><main id="page"></main><footer class="page-footer"><span>StockFlow by Muhammad Irfan · Keep business moving.</span><span>Prices in IDR + MYR · Dates in WIB (UTC+7)</span></footer></div></div>`;
    headerStatus();renderPage();renderPending();
  }
  function renderPending(){const b=document.querySelector('#pending-banner');if(!b)return;const p=pending();b.innerHTML=p?`<div class="pending-banner"><span>A save is awaiting confirmation. Retry it before starting another change.</span><button class="button small" data-action="retry">Retry pending save</button></div>`:'';}
  function title(kicker,heading,sub,actions=''){return `<div class="page-heading"><div><span class="eyebrow">${kicker}</span><h1>${heading}</h1><p>${sub}</p></div><div class="heading-actions">${actions}</div></div>`;}
  let cartObserver;
  function renderPage(){const page=document.querySelector('#page');if(!page)return;page.innerHTML=({dashboard:dashboard,sale:salePage,inventory:inventory,history:history,settings:settings}[S.view])();cartObserver?.disconnect();const cart=document.querySelector('#sale-cart');if(cart){cartObserver=new IntersectionObserver(entries=>{const shortcut=document.querySelector('.mobile-cart-button');if(shortcut)shortcut.hidden=entries[0].isIntersecting;});cartObserver.observe(cart);}}
  function badge(p){return `<span class="badge ${p.stock===0?'danger':p.stock<=p.lowStock?'warning':'success'}">${p.stock===0?'Out of stock':p.stock<=p.lowStock?'Low stock':'In stock'}</span>`;}
  function empty(titleText,description,action=''){return `<div class="empty">${icon('receipt')}<h3>${titleText}</h3><p>${description}</p>${action}</div>`;}
  function dashboard(){
    const m=C.summary(S.db),recent=sales().slice(0,5),ps=products(),days=Array.from({length:7},(_,i)=>{const at=Date.now()-(6-i)*86400000;const key=C.dateKey(at);return {label:new Intl.DateTimeFormat('en-GB',{weekday:'short',timeZone:'Asia/Jakarta'}).format(at),value:sales().filter(s=>s.status==='completed'&&C.dateKey(s.at)===key).reduce((n,s)=>n+s.total,0)};}),max=Math.max(1,...days.map(d=>d.value));
    const top={};sales().filter(s=>s.status==='completed').forEach(s=>s.items.forEach(i=>{top[i.productId] ||= {name:i.name,quantity:0,total:0};top[i.productId].quantity+=i.quantity;top[i.productId].total+=i.lineTotal;}));
    return title('YOUR BUSINESS, AT A GLANCE','A clear view of your day.','Here’s how your Sarawak collection is doing.',`<span class="date-pill">${new Intl.DateTimeFormat('en-GB',{dateStyle:'long',timeZone:'Asia/Jakarta'}).format(new Date())}</span><button class="button primary" data-view="sale">${icon('plus')} New sale</button>`)+
    `<div class="metrics"><article class="metric featured"><div><span>Today’s sales</span>${icon('sale')}</div><strong>${money(m.todayRevenue)}<small class="metric-myr">${myr(m.todayRevenue)}</small></strong><small>${m.todayCount} completed ${m.todayCount===1?'sale':'sales'} today</small></article><article class="metric"><div><span>Total revenue</span>${icon('dashboard')}</div><strong>${money(m.revenue)}<small class="metric-myr">${myr(m.revenue)}</small></strong><small>${m.count} completed sales · all time</small></article><article class="metric"><div><span>Items sold</span>${icon('check')}</div><strong>${m.unitsSold}<em> units</em></strong><small>Across your whole collection</small></article><article class="metric"><div><span>Stock on hand</span>${icon('box')}</div><strong>${m.stock}<em> units</em></strong><small>${ps.length} active products</small></article></div>
    ${!ps.length?`<div class="import-callout"><div><h3>Your inventory is ready for its first products.</h3><p>Load the 20 items and 117 units from your SUCCESS26 catalogue, or add your own.</p></div><button class="button primary" data-action="seed" ${S.ready?'':'disabled'}>Load SUCCESS26 catalogue</button></div>`:''}
    <div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><h2>Sales over time</h2><p>Your last 7 days, in IDR</p></div><span class="subtle-chip">7 days</span></div><div class="chart" role="img" aria-label="Daily sales: ${days.map(d=>d.label+' '+money(d.value)).join(', ')}">${days.map(d=>`<div class="chart-column"><span class="chart-value">${d.value?money(d.value):'—'}</span><div class="bar-track"><div class="bar ${d.value?'':'zero'}" style="height:${d.value?Math.max(3,Math.round(d.value/max*100)):2}%"></div></div><span>${d.label}</span></div>`).join('')}</div>${m.count===0?'<div class="chart-note">Your sales story starts with your first sale.</div>':''}</section><section class="panel attention"><div class="panel-head"><div><h2>Stock watch</h2><p>A little attention goes a long way</p></div><span class="count-chip">${m.low.length}</span></div>${m.low.length?`<div class="stock-watch">${m.low.slice(0,4).map(p=>`<button class="watch-row" data-action="stock" data-id="${esc(p.id)}"><div class="tiny-image">${image(p)}</div><span><strong>${esc(canonicalName(p.name))}</strong><small>${esc(p.sku)}</small></span><span class="stock-number">${p.stock}<small>left</small></span></button>`).join('')}</div><button class="text-button panel-link" data-view="inventory">View inventory ${icon('arrow')}</button>`:empty('All stocked up','Low-stock products will appear here.')}</section></div>
    <div class="dashboard-bottom"><section class="panel"><div class="panel-head"><div><h2>Recent sales</h2><p>The latest from your counter</p></div><button class="text-button" data-view="history">View all ${icon('arrow')}</button></div>${recent.length?salesTable(recent):empty('Ready for your first sale','Pick a product, choose a quantity, and you’re on your way.','<button class="button secondary" data-view="sale">Record a sale '+icon('arrow')+'</button>')}</section><section class="collection-card"><span class="eyebrow">FROM SARAWAK, WITH LOVE</span><h2>A collection<br>worth sharing.</h2><p>Handcrafted pieces.<br>Everyday favourites.<br>All in one inventory.</p><div class="collection-photos"><img src="assets/product-16.jpg" alt="Sarawak Batik Owl"><img src="assets/product-12.jpg" alt="Pua Kumbu scarf"></div><button class="text-button" data-view="inventory">Explore your products ${icon('arrow')}</button></section></div>`;
  }
  function filterBar(){return `<div class="search-field">${icon('search')}<input id="product-search" type="search" placeholder="Search products or SKU…" aria-label="Search products" value="${esc(S.search)}"></div><select id="category-filter" aria-label="Filter by category"><option>All categories</option>${[...new Set(products().map(p=>p.category))].sort().map(c=>`<option ${S.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select>`;}
  function filteredProducts(){return products().filter(p=>(S.category==='All categories'||p.category===S.category)&&(p.name+' '+p.sku).toLowerCase().includes(S.search.toLowerCase()));}
  function productGrid(){const ps=filteredProducts();return ps.length?ps.map(p=>{const inCart=S.cart.find(x=>x.productId===p.id)?.quantity||0;return `<button class="product-card" data-action="add-cart" data-id="${esc(p.id)}" ${p.stock<=inCart||!S.ready?'disabled':''}><div class="product-photo">${image(p)}<span class="stock-pill ${p.stock<=p.lowStock?'low':''}">${p.stock===0?'Sold out':p.stock+' in stock'}</span></div><div class="product-info"><small>${esc(p.category)}</small><h3>${esc(canonicalName(p.name))}</h3><div><span class="product-price">${money(p.price)}<small>${myr(p.price)}</small></span><span class="add-circle">+</span></div></div></button>`;}).join(''):empty('No products found','Try another search or add a product in Inventory.');}
  function salePage(){const qr=S.payment==='QR / bank transfer'?paymentQr():'';return title('AT THE COUNTER','Make it a sale.','Choose your products. We’ll take care of the stock count.')+`<div class="sale-layout"><section><div class="filter-bar">${filterBar()}</div><div class="product-grid" id="product-results">${productGrid()}</div></section><aside class="cart panel" id="sale-cart"><div class="panel-head"><div><h2>Current sale</h2><p id="cart-count">${S.cart.reduce((n,i)=>n+i.quantity,0)} items added</p></div>${icon('sale')}</div><div id="cart-lines">${cartLines()}</div><div class="cart-details"><label>Customer <span class="optional">optional</span><input id="customer" maxlength="160" placeholder="Walk-in customer" value="${esc(S.customer)}"></label><label>WhatsApp number <span class="optional">for e-invoice</span><div class="phone-input"><span>+62</span><input id="customer-phone" inputmode="tel" autocomplete="tel" maxlength="24" placeholder="812 3456 7890" value="${esc(String(S.customerPhone||'+62').replace(/^\+?62/,''))}"></div></label><label>Payment method<select id="payment">${['Cash','QR / bank transfer','Card'].map(x=>`<option ${S.payment===x?'selected':''}>${x}</option>`).join('')}</select></label><div id="payment-qr-slot">${qr}</div><label>Note <span class="optional">optional</span><textarea id="sale-note" rows="2" maxlength="500" placeholder="Anything to remember?">${esc(S.note)}</textarea></label><div class="cart-total"><span>Total <small>IDR + MYR</small></span><strong id="cart-total">${money(S.cart.reduce((n,i)=>n+i.quantity*i.unitPrice,0))}<small>${myr(S.cart.reduce((n,i)=>n+i.quantity*i.unitPrice,0))}</small></strong></div><button class="button primary wide" id="complete-sale" data-action="checkout" ${!S.cart.length||!S.ready?'disabled':''}>${icon('check')} Complete sale</button><p class="fine center">After saving, you can send the e-invoice straight to the customer’s WhatsApp.</p></div></aside></div><button class="button primary mobile-cart-button" data-action="review-cart">${icon('sale')} Review current sale ${icon('arrow')}</button>`;}
  function cartLines(){return S.cart.length?S.cart.map(i=>{const p=S.db.products[i.productId];return `<div class="cart-line"><div class="cart-line-title"><strong>${esc(canonicalName(p?.name)||'Unavailable product')}</strong><button class="icon-button" data-action="remove-cart" data-id="${esc(i.productId)}" aria-label="Remove ${esc(canonicalName(p?.name))}">${icon('close')}</button></div><div class="line-inputs"><label>Qty<input type="number" required min="1" max="${p?.stock||0}" step="1" data-cart-qty="${esc(i.productId)}" value="${i.quantity}"></label><label>Unit price · IDR <span class="optional">MYR shown automatically</span><input type="number" required min="0" max="1000000000" step="1" data-cart-price="${esc(i.productId)}" value="${i.unitPrice}"></label></div><div class="line-subtotal">${p?.promoPrice!=null?`<button class="text-button" data-action="promo" data-id="${esc(i.productId)}">Use promo ${money(p.promoPrice)}</button>`:'<span></span>'}<strong>${money(i.quantity*i.unitPrice)}<small>${myr(i.quantity*i.unitPrice)}</small></strong></div></div>`;}).join(''):`<div class="empty cart-empty">${icon('sale')}<h3>Your counter is clear</h3><p>Click a product to add it to this sale.</p></div>`;}
  function updateCart(){document.querySelector('#cart-lines').innerHTML=cartLines();document.querySelector('#cart-count').textContent=S.cart.reduce((n,i)=>n+i.quantity,0)+' items added';{const total=S.cart.reduce((n,i)=>n+i.quantity*i.unitPrice,0);document.querySelector('#cart-total').innerHTML=money(total)+'<small>'+myr(total)+'</small>';}document.querySelector('#complete-sale').disabled=!S.cart.length||!S.ready;document.querySelector('#product-results').innerHTML=productGrid();}
  function inventoryRows(){const ps=filteredProducts();return ps.length?`<div class="table-scroll"><table><thead><tr><th>Product</th><th>Category</th><th>Price · IDR + MYR</th><th>Cost · MYR</th><th>Stock</th><th>Status</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody>${ps.map(p=>`<tr><td><div class="table-product"><div class="tiny-image">${image(p)}</div><div><strong>${esc(canonicalName(p.name))}</strong><small>${esc(p.sku)}</small></div></div></td><td>${esc(p.category)}</td><td class="money-cell">${money(p.price)}<small>${myr(p.price)}</small>${p.promoPrice!=null?`<small>Promo ${money(p.promoPrice)} · ${myr(p.promoPrice)}</small>`:''}</td><td>${rm(p.costRM)}</td><td><strong>${p.stock}</strong><small>units</small></td><td>${badge(p)}</td><td><div class="row-actions"><button class="text-button" data-action="stock" data-id="${esc(p.id)}">Adjust stock</button><button class="text-button muted" data-action="edit-product" data-id="${esc(p.id)}">Edit</button></div></td></tr>`).join('')}</tbody></table></div>`:empty('No products found','Add a product or change your filters.');}
  function inventory(){return title('EVERY ITEM, ACCOUNTED FOR','Your inventory.','Manage products, prices, and the stock you have on hand.',`<button class="button secondary" data-action="export-stock">${icon('download')} Export stock</button><button class="button primary" data-action="new-product">${icon('plus')} Add product</button>`)+`<div class="inventory-summary"><span><strong>${products().length}</strong> products</span><span><strong>${C.summary(S.db).stock}</strong> total units</span><span class="low-label">${icon('alert')} ${C.summary(S.db).low.length} need attention</span></div><section class="panel inventory-panel"><div class="filter-bar">${filterBar()}</div><div id="product-results">${inventoryRows()}</div></section><div class="source-note">SUCCESS26 catalogue prices are entered in full rupiah (80 ribu = Rp 80.000). Purchase costs are shown in MYR; selling prices also show an MYR estimate using the reference rate 1 MYR = Rp 4,333.17 (15 Sep 2026). Missing costs are shown as “Not supplied”.</div>`;}
  function historyItems(){return sales().filter(s=>(S.historyStatus==='all'||s.status===S.historyStatus)&&(!S.historyDate||C.dateKey(s.at)===S.historyDate)&&[s.id,s.customer,...s.items.map(i=>canonicalName(i.name))].join(' ').toLowerCase().includes(S.historySearch.toLowerCase()));}
  function salesTable(list){return `<div class="table-scroll"><table><thead><tr><th>Sale</th><th>Customer</th><th>Items</th><th>Total · IDR + MYR</th><th>Status</th><th></th></tr></thead><tbody>${list.map(s=>`<tr><td><strong>#${esc(s.id.slice(-8).toUpperCase())}</strong><small>${when(s.at)}</small></td><td><strong>${esc(s.customer||'Walk-in customer')}</strong></td><td>${s.items.reduce((n,i)=>n+i.quantity,0)}<small>${esc(s.payment)}</small></td><td class="money-cell">${money(s.total)}<small>${myr(s.total)}</small></td><td><span class="badge ${s.status==='voided'?'neutral':'success'}">${s.status==='voided'?'Voided':'Completed'}</span></td><td><button class="text-button" data-action="receipt" data-id="${esc(s.id)}">View ${icon('arrow')}</button></td></tr>`).join('')}</tbody></table></div>`;}
  function historyResults(){const list=historyItems();return `<div class="history-total"><span>${list.length} matching sales</span><strong>Completed total: ${money(list.filter(s=>s.status==='completed').reduce((n,s)=>n+s.total,0))} · ${myr(list.filter(s=>s.status==='completed').reduce((n,s)=>n+s.total,0))}</strong></div>`+(list.length?salesTable(list):empty('No sales here yet','Completed sales will appear here. You can search and export them anytime.'));}
  function history(){return title('THE FULL PICTURE','Every sale has a story.','Review your transactions, export sales, or correct a sale by voiding it.',`<button class="button secondary" data-action="export-sales">${icon('download')} Export sales</button>`)+`<section class="panel"><div class="filter-bar history-filters"><div class="search-field">${icon('search')}<input id="history-search" type="search" aria-label="Search sales" placeholder="Search sale, product, customer…" value="${esc(S.historySearch)}"></div><input type="date" id="history-date" aria-label="Filter by sale date in WIB" value="${esc(S.historyDate)}"><select id="history-status" aria-label="Filter by sale status">${[['all','All statuses'],['completed','Completed'],['voided','Voided']].map(([v,t])=>`<option value="${v}" ${S.historyStatus===v?'selected':''}>${t}</option>`).join('')}</select><button class="text-button" data-action="clear-history">Clear</button></div><div id="history-results">${historyResults()}</div></section>`;}
  function setupContent(){return `<div class="setup-steps"><section><span class="step-number">01</span><div><h3>Shared Firebase workspace</h3><p>StockFlow opens directly with no Cashier ID, signup or password screen. Inventory and sales continue using the existing Firebase Realtime Database workspace.</p></div></section><section><span class="step-number">02</span><div><h3>WhatsApp e-invoices</h3><p>Add the customer’s Indonesian WhatsApp number at checkout. StockFlow defaults to <code>+62</code> and prepares a ready-to-send e-invoice after the sale.</p></div></section><section><span class="step-number">03</span><div><h3>Shared between devices</h3><p>Devices connected to the same StockFlow site and Firebase RTDB see the same inventory and sales. Use Download backup whenever you want an offline copy.</p></div></section></div>`;}
  function settings(){const missing=products().filter(p=>p.costRM==null);return title('MAKE YOURSELF AT HOME','Workspace setup.','Your shared StockFlow workspace is connected through Firebase RTDB — no cashier login required.')+`<div class="settings-grid"><section class="panel"><div class="panel-head"><div><h2>Shared workspace</h2><p>Firebase Realtime Database · one StockFlow dataset</p></div></div><div class="panel-body">${setupContent()}</div></section><div><section class="panel"><div class="panel-head"><h2>Your product catalogue</h2></div><div class="panel-body"><p>20 products · 117 opening units<br>Product Sarawak SUCCESS26</p><p class="fine">“SALES” in the catalogue is treated as an optional promotional unit price. Standard price is used by default.</p><button class="button secondary wide" data-action="seed" ${products().length||!S.ready?'disabled':''}>Load SUCCESS26 catalogue</button>${products().length?'<p class="fine">An inventory already exists. Edit products in Inventory.</p>':''}${missing.length?`<p class="source-note">${missing.length} products need a purchase cost. Revenue is recorded in IDR and shown with an MYR reference conversion.</p>`:''}</div></section><section class="panel backup-panel"><div class="panel-head"><h2>Keep a copy</h2></div><div class="panel-body"><p>Download all inventory, sales, and stock adjustments as a JSON backup.</p><button class="button secondary wide" data-action="backup">${icon('download')} Download backup</button><p class="fine">StockFlow by Muhammad Irfan.</p></div></section></div></div>`;}
  async function start(){
    S.store=F.createStore();S.db=C.blank();S.ready=false;S.lastSync=null;S.syncError='';S.cart=[];S.view='dashboard';showWelcome();
    const begun=Date.now();try{S.db=await S.store.read();S.ready=true;S.lastSync=Date.now();}catch(e){S.syncError=e.message;toast(e.message,true);}const wait=Math.max(0,1650-(Date.now()-begun));if(wait)await new Promise(r=>setTimeout(r,wait));shell();
  }
  async function sync(){if(!S.store||S.busy)return;const activeStore=S.store;try{const data=await activeStore.read();if(S.store!==activeStore)return;const changed=JSON.stringify(data)!==JSON.stringify(S.db);S.db=data;S.ready=true;S.syncError='';S.lastSync=Date.now();headerStatus();if(changed&&!modal.open){if(S.view==='sale')updateCart();else if(S.view==='inventory')document.querySelector('#product-results').innerHTML=inventoryRows();else if(S.view==='history')document.querySelector('#history-results').innerHTML=historyResults();else renderPage();}}catch(e){if(S.store!==activeStore)return;S.syncError=e.message;headerStatus();}}
  async function commit(cmd,successText){
    if(S.busy)return false;if(!S.ready){toast('Open the workspace before saving.',true);return false;}
    const prev=pending();if(prev&&prev.id!==cmd.id){toast('Retry the pending save first. It may already have reached the database.',true);renderPending();return false;}
    // Validate locally first; invalid input must never become an unresolved network operation.
    try{C.apply(S.db,cmd,S.store.actor());}catch(e){toast(e.message,true);return false;}
    sessionStorage.setItem(pendingKey(),JSON.stringify(cmd));setBusy(true);
    try{S.db=await S.store.mutate(cmd);sessionStorage.removeItem(pendingKey());S.lastSync=Date.now();S.syncError='';setBusy(false);modal.close();if(cmd.type==='sale'){S.cart=[];S.customer='';S.customerPhone='+62';S.note='';S.payment='Cash';}shell();toast(successText);return true;}
    catch(e){
      // A successful read can resolve an uncertain PUT response without recording the operation twice.
      try{const fresh=await S.store.read();S.db=fresh;if(fresh.operations?.[cmd.id]){sessionStorage.removeItem(pendingKey());setBusy(false);modal.close();if(cmd.type==='sale'){S.cart=[];S.customer='';S.customerPhone='+62';S.note='';}shell();toast('Save confirmed.');return true;}
        if(!e.ambiguous)sessionStorage.removeItem(pendingKey());
      }catch{ /* Keep the stable operation ID for a safe retry after reconnecting. */ }
      setBusy(false);renderPending();headerStatus();toast(e.message,true);return false;
    }
  }
  function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function productDialog(productId){const p=productId?S.db.products[productId]:{id:id(),name:'',sku:'',category:'Accessories',stock:0,costRM:null,price:0,promoPrice:null,lowStock:3,note:'',active:true};
    openDialog(`<span class="eyebrow">INVENTORY</span><h2>${productId?'Edit product':'A new addition.'}</h2><p>${productId?'Update product details. Use Adjust stock to change quantities.':'Add the details and opening stock for this product.'}</p><form id="product-form" data-id="${esc(p.id)}" data-updated="${p.updatedAt||''}"><div class="form-grid"><label class="full">Product name<input name="name" required maxlength="160" value="${esc(canonicalName(p.name))}"></label><label>SKU<input name="sku" required maxlength="40" value="${esc(p.sku)}"></label><label>Category<input name="category" required maxlength="60" value="${esc(p.category)}" list="categories"><datalist id="categories">${['Accessories','Textiles','Bags & purses','Crafts','Fragrance','Food & drink'].map(c=>`<option>${c}</option>`).join('')}</datalist></label><label>Selling price · IDR<input name="price" type="number" required min="0" max="1000000000" step="1" value="${p.price}"></label><label>Promo price · IDR <span class="optional">optional</span><input name="promoPrice" type="number" min="0" max="1000000000" step="1" value="${p.promoPrice??''}"></label><label>Purchase cost · MYR <span class="optional">optional</span><input name="costRM" type="number" min="0" max="1000000" step="0.01" value="${p.costRM??''}"></label><label>Low-stock alert at<input name="lowStock" type="number" required min="0" max="1000000" step="1" value="${p.lowStock}"></label>${!productId?'<label class="full">Opening stock<input name="stock" type="number" required min="0" max="1000000" step="1" value="0"></label>':''}<label class="full">Notes<textarea name="note" maxlength="500" rows="2">${esc(p.note)}</textarea></label></div><div class="dialog-actions"><button type="button" class="button secondary" data-action="close">Cancel</button><button class="button primary" type="submit">Save product</button></div></form>`);
  }
  function stockDialog(productId){const p=S.db.products[productId];openDialog(`<span class="eyebrow">STOCK ADJUSTMENT</span><h2>${esc(canonicalName(p.name))}</h2><p>Currently <strong>${p.stock} units</strong> in stock. Adjustments are recorded in your stock history.</p><form id="stock-form" data-id="${esc(p.id)}"><label>Change in quantity<input name="delta" type="number" required min="-1000000" max="1000000" step="1" placeholder="e.g. 10 to add, -2 to remove"></label><label>Reason<input name="reason" required maxlength="200" placeholder="Restock, damaged item, count correction…"></label><div class="dialog-actions"><button type="button" class="button secondary" data-action="close">Cancel</button><button class="button primary" type="submit">Save adjustment</button></div></form><h3 class="movement-heading">Recent stock movements</h3><div class="movements">${Object.values(S.db.movements).filter(m=>m.productId===p.id).sort((a,b)=>b.at-a.at).slice(0,5).map(m=>`<div><span><strong>${esc(m.reason)}</strong><small>${when(m.at)}</small></span><b>${m.delta>0?'+':''}${m.delta}</b></div>`).join('')||'<p>No adjustments yet.</p>'}</div>`);}
  function receipt(saleId){const s=S.db.sales[saleId],hasPhone=normalizePhone(s.customerPhone)&&normalizePhone(s.customerPhone)!=='62';openDialog(`<div class="invoice-brand"><span>StockFlow<span class="brand-dot">.</span></span><small>by Muhammad Irfan</small></div><span class="eyebrow">E-INVOICE · #${esc(s.id.slice(-8).toUpperCase())}</span><h2>${s.status==='voided'?'Voided sale':'Sale recorded.'}</h2><p>${when(s.at)} WIB</p><div class="receipt-meta"><span>Customer<strong>${esc(s.customer||'Walk-in customer')}</strong>${s.customerPhone?`<small>${esc(s.customerPhone)}</small>`:''}</span><span>Payment<strong>${esc(s.payment)}</strong></span></div>${s.payment==='QR / bank transfer'?paymentQr(true):''}<div class="receipt-lines">${s.items.map(i=>`<div><span><strong>${esc(canonicalName(i.name))}</strong><small>${i.quantity} × ${money(i.unitPrice)} · ${myr(i.unitPrice)}</small></span><b>${money(i.lineTotal)}<small>${myr(i.lineTotal)}</small></b></div>`).join('')}</div><div class="cart-total"><span>Total · IDR + MYR</span><strong>${money(s.total)}<small>${myr(s.total)}</small></strong></div>${s.note?`<p>Note: ${esc(s.note)}</p>`:''}${s.status==='voided'?`<p class="source-note">Voided on ${when(s.voidAt)}. Stock restored.<br>Reason: ${esc(s.voidReason)}</p>`:`<div class="invoice-actions"><button class="button whatsapp wide" data-action="whatsapp" data-id="${esc(s.id)}" ${hasPhone?'':'disabled'}>${icon('phone')} Send e-invoice via WhatsApp</button>${hasPhone?'':'<small>Add a customer WhatsApp number to enable sending.</small>'}</div><button class="text-button danger-text" data-action="void-dialog" data-id="${esc(s.id)}">Void sale and restore stock</button>`}<div class="dialog-actions"><button class="button secondary" data-action="close">Close</button></div>`);}
  document.addEventListener('click',async e=>{
    const target=e.target.closest('[data-action],[data-view]');if(!target)return;e.preventDefault();if(S.busy)return;
    if(target.dataset.view){if(!S.store)return;S.view=target.dataset.view;S.search='';S.category='All categories';shell();window.scrollTo(0,0);return;}
    const action=target.dataset.action,pid=target.dataset.id;
    try{
      if(action==='qr')return openDialog(`<div class="qr-dialog"><span class="eyebrow">PAYMENT QR</span><h2>Scan to pay.</h2><img src="assets/duitnow-qr.png" alt="DuitNow Malaysia National QR"><p>Malaysia National QR · DuitNow</p></div><div class="dialog-actions"><button class="button primary" data-action="close">Done</button></div>`);
      if(action==='whatsapp')return sendWhatsApp(pid);
      if(action==='review-cart'){document.querySelector('#sale-cart').scrollIntoView({behavior:'smooth',block:'start'});return;}
      if(action==='close')return closeDialog();
      if(action==='refresh'){await sync();if(S.syncError)toast(S.syncError,true);else toast('Workspace is up to date.');return;}
      if(action==='seed')return await commit({id:id(),at:Date.now(),type:'seed',products:StockFlowCatalog},'20 products and 117 units loaded.');
      if(action==='retry'){const cmd=pending();if(cmd)await commit(cmd,'Pending save confirmed.');return;}
      if(action==='new-product')return productDialog();if(action==='edit-product')return productDialog(pid);if(action==='stock')return stockDialog(pid);
      if(action==='add-cart'){if(pending()){toast('Resolve the pending save first.',true);return;}const p=S.db.products[pid],line=S.cart.find(i=>i.productId===pid);if(line){if(line.quantity>=p.stock)return;line.quantity++;}else S.cart.push({productId:pid,quantity:1,unitPrice:p.price});updateCart();return;}
      if(action==='remove-cart'){S.cart=S.cart.filter(i=>i.productId!==pid);updateCart();return;}
      if(action==='promo'){S.cart.find(i=>i.productId===pid).unitPrice=S.db.products[pid].promoPrice;updateCart();return;}
      if(action==='checkout'){const invalid=[...document.querySelectorAll('#cart-lines input')].find(el=>!el.checkValidity()||el.value==='');if(invalid){invalid.reportValidity();toast('Check the quantities and prices before saving.',true);return;}const cmd={id:id(),at:Date.now(),type:'sale',items:structuredClone(S.cart),customer:S.customer,customerPhone:S.customerPhone,payment:S.payment,note:S.note};if(await commit(cmd,'Sale recorded and stock updated.'))receipt(cmd.id);return;}
      if(action==='receipt')return receipt(pid);
      if(action==='void-dialog')return openDialog(`<span class="eyebrow">CORRECT A SALE</span><h2>Void this sale?</h2><p>All items will be returned to stock and ${money(S.db.sales[pid].total)} (${myr(S.db.sales[pid].total)}) excluded from revenue. The original record stays in your history.</p><form id="void-form" data-id="${esc(pid)}"><label>Reason<input name="reason" required maxlength="200" placeholder="e.g. customer cancelled"></label><div class="dialog-actions"><button class="button secondary" type="button" data-action="close">Keep sale</button><button class="button danger-button" type="submit">Void and restore stock</button></div></form>`);
      if(action==='clear-history'){S.historySearch='';S.historyDate='';S.historyStatus='all';renderPage();return;}
      if(action==='export-sales')return download('StockFlow-sales-'+C.dateKey(Date.now())+'.csv',C.salesCsv(historyItems()),'text/csv;charset=utf-8');
      if(action==='export-stock'){const rows=[['SKU','Product','Category','Stock','Selling price IDR','Selling price MYR (reference)','Promo price IDR','Promo price MYR (reference)','Purchase cost MYR','Low stock level'],...products().map(p=>[p.sku,canonicalName(p.name),p.category,p.stock,p.price,(p.price/IDR_PER_MYR).toFixed(2),p.promoPrice??'',p.promoPrice==null?'':(p.promoPrice/IDR_PER_MYR).toFixed(2),p.costRM??'',p.lowStock])];const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+\-@\t\r]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');return download('StockFlow-inventory.csv',csv,'text/csv;charset=utf-8');}
      if(action==='backup')return download('StockFlow-backup-'+C.dateKey(Date.now())+'.json',JSON.stringify({exportedAt:new Date().toISOString(),mode:'firebase-rtdb-stockflow',data:S.db},null,2),'application/json');
    }catch(err){toast(err.message,true);}
  });
  document.addEventListener('submit',async e=>{
    e.preventDefault();const f=e.target;if(S.busy)return;const d=new FormData(f),get=k=>String(d.get(k)||'');
    if(f.id==='product-form'){const old=S.db.products[f.dataset.id];const product={...(old||{}),id:f.dataset.id,name:get('name'),sku:get('sku'),category:get('category'),price:Number(get('price')),promoPrice:get('promoPrice')===''?null:Number(get('promoPrice')),costRM:get('costRM')===''?null:Number(get('costRM')),lowStock:Number(get('lowStock')),stock:old?old.stock:Number(get('stock')),note:get('note'),active:true};await commit({id:id(),at:Date.now(),type:'product',product,expectedUpdatedAt:Number(f.dataset.updated)},'Product saved.');}
    if(f.id==='stock-form')await commit({id:id(),at:Date.now(),type:'stock',productId:f.dataset.id,delta:Number(get('delta')),reason:get('reason')},'Stock adjustment saved.');
    if(f.id==='void-form')await commit({id:id(),at:Date.now(),type:'void',saleId:f.dataset.id,reason:get('reason')},'Sale voided. Stock has been restored.');
  });
  document.addEventListener('input',e=>{const el=e.target;if(el.id==='product-search'){S.search=el.value;document.querySelector('#product-results').innerHTML=S.view==='sale'?productGrid():inventoryRows();}if(el.id==='history-search'){S.historySearch=el.value;document.querySelector('#history-results').innerHTML=historyResults();}if(el.id==='customer')S.customer=el.value;if(el.id==='customer-phone')S.customerPhone='+62'+el.value.replace(/\D/g,'').replace(/^62/,'');if(el.id==='sale-note')S.note=el.value;
    if(el.dataset.cartQty||el.dataset.cartPrice){const line=S.cart.find(i=>i.productId===(el.dataset.cartQty||el.dataset.cartPrice)),value=Number(el.value);if(el.value!==''&&el.checkValidity()&&Number.isSafeInteger(value)){line[el.dataset.cartQty?'quantity':'unitPrice']=value;{const subtotal=line.quantity*line.unitPrice;el.closest('.cart-line').querySelector('.line-subtotal strong').innerHTML=money(subtotal)+'<small>'+myr(subtotal)+'</small>';}document.querySelector('#cart-count').textContent=S.cart.reduce((n,i)=>n+i.quantity,0)+' items added';{const total=S.cart.reduce((n,i)=>n+i.quantity*i.unitPrice,0);document.querySelector('#cart-total').innerHTML=money(total)+'<small>'+myr(total)+'</small>';}document.querySelector('#product-results').innerHTML=productGrid();}document.querySelector('#complete-sale').disabled=[...document.querySelectorAll('#cart-lines input')].some(x=>!x.checkValidity()||x.value==='')||!S.ready;}
  });
  document.addEventListener('change',e=>{const el=e.target;if(el.id==='category-filter'){S.category=el.value;document.querySelector('#product-results').innerHTML=S.view==='sale'?productGrid():inventoryRows();}if(el.id==='payment'){S.payment=el.value;const slot=document.querySelector('#payment-qr-slot');if(slot)slot.innerHTML=S.payment==='QR / bank transfer'?paymentQr():'';}if(el.id==='history-date'||el.id==='history-status'){S[el.id==='history-date'?'historyDate':'historyStatus']=el.value;document.querySelector('#history-results').innerHTML=historyResults();}
    if(el.dataset.cartQty||el.dataset.cartPrice){const pid=el.dataset.cartQty||el.dataset.cartPrice,line=S.cart.find(i=>i.productId===pid),value=Number(el.value);if(!el.checkValidity()||!Number.isSafeInteger(value)){el.reportValidity();return;}line[el.dataset.cartQty?'quantity':'unitPrice']=value;updateCart();}
  });
  modal.addEventListener('cancel',e=>{if(S.busy)e.preventDefault();});
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync();});
  setInterval(()=>{if(!document.hidden)sync();},15000);
  window.addEventListener('beforeunload',e=>{if(S.cart.length||S.busy||(S.store&&pending())){e.preventDefault();e.returnValue='';}});
  start();
})();
